import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api } from '../lib/api';

export default function EditProduct() {
  const { id } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState(null); const [image, setImage] = useState(null); const [preview, setPreview] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { api.getProduct(id).then((p) => setForm({ title:p.title, description:p.description, price:p.price, category:p.category, gender:p.gender || 'Unisex', volume:p.volume || '' })).catch((e) => setError(e.message)); }, [id]);
  if (!form) return <div className="min-h-screen pt-36 text-center text-stone-600">{error || 'Loading listing…'}</div>;
  const set = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const payload = new FormData(); Object.entries({ ...form, price:Number(form.price) }).forEach(([key, value]) => payload.append(key, value)); if (image) payload.append('image', image); const product = await api.updateProduct(id, payload); navigate(`/product/${product.id}`); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <div className="min-h-screen bg-[#f8f7f4] pt-28 pb-20 px-4 sm:px-6"><div className="max-w-2xl mx-auto rounded-[2rem] border border-stone-200 bg-white p-7 md:p-10 shadow-[0_20px_70px_rgba(56,40,20,.10)]"><p className="eyebrow">Seller dashboard</p><h1 className="font-serif text-4xl font-bold text-stone-900">Edit your listing</h1><form onSubmit={submit} className="mt-8 grid gap-5"><Field label="Product title"><input required value={form.title} onChange={set('title')} /></Field><Field label="Description"><textarea required rows="5" value={form.description} onChange={set('description')} /></Field><div className="grid sm:grid-cols-2 gap-5"><Field label="Price (₹)"><input required type="number" min="0" value={form.price} onChange={set('price')} /></Field><Field label="Category"><input required value={form.category} onChange={set('category')} /></Field></div><div className="grid sm:grid-cols-2 gap-5"><Field label="For"><select value={form.gender} onChange={set('gender')}><option>Unisex</option><option>Men</option><option>Women</option></select></Field><Field label="Bottle size"><input value={form.volume} onChange={set('volume')} /></Field></div><label className="rounded-2xl border border-dashed border-stone-300 p-5 text-center transition hover:border-amber-500 hover:bg-amber-50"><span className="block text-sm font-semibold text-stone-800">Replace product photo</span><span className="mt-1 block text-xs text-stone-500">Optional — JPG, PNG, or WebP up to 5 MB</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; setImage(file || null); setPreview(file ? URL.createObjectURL(file) : ''); }} className="mt-3 block w-full text-sm text-stone-600 file:mr-4 file:rounded-full file:border-0 file:bg-stone-900 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white" />{preview && <img src={preview} alt="New product photo preview" className="mx-auto mt-4 h-40 rounded-xl object-cover" />}</label>{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<button disabled={saving} className="mt-2 rounded-full bg-stone-900 py-4 font-semibold text-white transition hover:bg-amber-700 disabled:opacity-60">{saving ? 'Saving changes…' : 'Save changes'}</button></form></div></div>;
}
function Field({ label, children }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-stone-700">{label}</span>{React.cloneElement(children, { className: 'form-control' })}</label>; }