import React from 'react';
import { Link } from 'react-router-dom';
import { useCart } from '../context/CartContext';
import { useWishlist } from '../context/WishlistContext';

const ProductCard = ({ product }) => {
  const { addToCart, isInCart } = useCart();
  const { toggleWishlist, isInWishlist } = useWishlist();
  const add = (event) => { event.preventDefault(); addToCart(product); };
  const wish = (event) => { event.preventDefault(); toggleWishlist(product); };
  return <Link to={`/product/${product.id}`} className="group block h-full"><article className="h-full overflow-hidden rounded-2xl border border-stone-200/80 bg-white shadow-[0_8px_26px_rgba(50,36,20,.06)] transition duration-500 hover:-translate-y-1 hover:border-amber-200 hover:shadow-[0_18px_38px_rgba(50,36,20,.15)]"><div className="relative aspect-[4/5] overflow-hidden bg-stone-100"><img src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-110" loading="lazy" onError={(event) => { event.currentTarget.src = 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=500&q=80'; }} /><div className="absolute inset-x-0 bottom-0 h-2/5 bg-gradient-to-t from-black/55 to-transparent opacity-0 transition group-hover:opacity-100" /><div className="absolute left-3 top-3 flex flex-col gap-2">{product.isNewArrival && <span className="rounded-full bg-[#191714] px-3 py-1 text-[10px] font-bold tracking-wider text-white">NEW</span>}{product.isBestSeller && <span className="rounded-full bg-amber-500 px-3 py-1 text-[10px] font-bold tracking-wider text-white">BEST SELLER</span>}</div><button onClick={wish} aria-label="Toggle wishlist" className="absolute right-3 top-3 grid h-10 w-10 place-items-center rounded-full bg-white/95 text-lg shadow-sm backdrop-blur transition hover:scale-110">{isInWishlist(product.id) ? <span className="text-red-500">♥</span> : <span className="text-stone-500">♡</span>}</button><button onClick={add} className="absolute inset-x-4 bottom-4 translate-y-3 rounded-xl bg-white py-3 text-sm font-bold text-stone-900 opacity-0 shadow-lg transition duration-300 group-hover:translate-y-0 group-hover:opacity-100">{isInCart(product.id) ? 'Added to cart' : 'Quick add'}</button></div><div className="flex min-h-40 flex-col p-5"><p className="text-[11px] font-bold uppercase tracking-[.15em] text-amber-700">{product.category}</p><h3 className="mt-2 line-clamp-1 text-lg font-semibold text-stone-900">{product.name}</h3><div className="mt-2 flex items-center gap-2"><span className="text-sm tracking-wider text-amber-500">★★★★★</span><span className="text-xs text-stone-500">{product.rating}</span></div><div className="mt-auto flex items-end justify-between pt-4"><p className="text-xl font-bold tracking-tight text-stone-950">₹{product.price.toLocaleString('en-IN')}</p><p className="rounded-md bg-stone-100 px-2 py-1 text-xs font-medium text-stone-500">{product.volume}</p></div></div></article></Link>;
};
export default ProductCard;